# Generated by Django 4.2.3 on 2023-07-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_product_best_selling_product_sold_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_count',
        ),
    ]
