# Generated by Django 4.2.3 on 2023-08-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=225)),
                ('shipping_address', models.TextField()),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('discount', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('cancel payment', 'cancel payment'), ('payment received', 'payment received'), ('order in progress', 'order in progress'), ('order received', 'order received')], default='pending', max_length=255)),
                ('payment_method', models.CharField(choices=[('Paystack', 'Paystack'), ('Transfer', 'Transfer')], default='Paystack', max_length=255)),
                ('payment_complete', models.BooleanField(default=False)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
    ]
